/* Main actions */
export const CHECK_RECENT_COMMENTS = 'CHECK_RECENT_COMMENTS';
export const SET_RECENT_COMMENT_EXIST = 'SET_RECENT_COMMENT_EXIST';
export const CLEAR_RECENT_COMMENT_EXIST = 'CLEAR_RECENT_COMMENT_EXIST';
export const FETCH_DEMOS = 'FETCH_DEMOS';
export const SET_DEMOS = 'SET_DEMOS';
export const SELECT_DEMO = 'SELECT_DEMO';
export const SELECT_DEMO_BY_ID = 'SELECT_DEMO_BY_ID';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const WRITE_COMMENT = 'WRITE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const FETCH_CATCHWORDS = 'FETCH_CATCHWORDS';
export const SET_CATCHWORDS = 'SET_CATCHWORDS';
export const ADD_CATCHWORD_COUNT = 'ADD_CATCHWORD_COUNT';